"""Agent Skill Discovery (Section 19).

Automatically discovers useful reusable procedures while agents solve tasks.
Skills represent: tool usage patterns, workflow templates, prompt strategies,
error recovery strategies, and data processing routines.
"""

import json
import logging

from sqlalchemy import select

from app.db.engine import async_session

logger = logging.getLogger(__name__)

# Minimum complexity threshold for skill proposals
MIN_TOOL_CALLS_FOR_PATTERN = 3
MIN_STEPS_FOR_PATTERN = 2


class SkillDiscoveryService:
    """Discovers reusable patterns from agent task execution."""

    _instance = None

    @classmethod
    def get_instance(cls) -> "SkillDiscoveryService":
        if cls._instance is None:
            cls._instance = cls()
        return cls._instance

    async def analyze_task_completion(
        self,
        agent_id: str,
        task_id: str,
        steps: list[dict],
        outcome: str,
    ) -> dict | None:
        """After successful task, analyze for reusable patterns.

        Returns a skill proposal dict if a novel pattern is found, else None.
        """
        if outcome != "success":
            return None

        if len(steps) < MIN_STEPS_FOR_PATTERN:
            return None

        # Extract tool usage sequences
        tool_sequence = self._extract_tool_sequence(steps)
        if len(tool_sequence) < MIN_TOOL_CALLS_FOR_PATTERN:
            return None

        # Check if similar pattern already exists
        existing = await self._find_similar_skill(tool_sequence)
        if existing:
            logger.debug("Similar skill already exists: %s", existing)
            return None

        # Generate skill proposal
        proposal = await self._generate_proposal(agent_id, task_id, steps, tool_sequence)
        if proposal:
            logger.info("Skill proposal generated by agent %s: %s", agent_id, proposal.get("name"))

        return proposal

    def _extract_tool_sequence(self, steps: list[dict]) -> list[str]:
        """Extract ordered tool call names from step history."""
        tools = []
        for step in steps:
            tool_calls = step.get("tool_calls", [])
            if isinstance(tool_calls, list):
                for tc in tool_calls:
                    name = tc.get("name") or tc.get("function", {}).get("name", "")
                    if name:
                        tools.append(name)
            elif isinstance(tool_calls, (int, float)):
                pass  # Just a count, skip
        return tools

    async def _find_similar_skill(self, tool_sequence: list[str]) -> str | None:
        """Check if a skill with a similar tool sequence already exists."""
        from app.models.skill import Skill

        sequence_key = ",".join(sorted(set(tool_sequence)))

        async with async_session() as session:
            stmt = select(Skill).where(Skill.is_active == True)  # noqa: E712
            result = await session.execute(stmt)
            skills = result.scalars().all()

        for skill in skills:
            if skill.metadata_json:
                try:
                    meta = json.loads(skill.metadata_json)
                    existing_tools = meta.get("tool_sequence", [])
                    existing_key = ",".join(sorted(set(existing_tools)))
                    # Simple overlap check — >70% tool overlap = similar
                    overlap = len(set(tool_sequence) & set(existing_tools))
                    total = max(len(set(tool_sequence)), 1)
                    if overlap / total > 0.7:
                        return skill.name
                except (json.JSONDecodeError, TypeError):
                    continue
        return None

    async def _generate_proposal(
        self,
        agent_id: str,
        task_id: str,
        steps: list[dict],
        tool_sequence: list[str],
    ) -> dict | None:
        """Generate a structured skill proposal from a successful pattern."""
        # Build a description from the steps
        step_summaries = []
        for i, step in enumerate(steps, 1):
            output = step.get("output_preview", step.get("output", ""))
            if isinstance(output, str) and len(output) > 200:
                output = output[:200] + "..."
            step_summaries.append(f"Step {i}: {output}")

        unique_tools = list(dict.fromkeys(tool_sequence))  # Preserve order, dedupe

        proposal = {
            "name": f"auto_skill_{task_id[:8]}",
            "description": f"Auto-discovered pattern using: {', '.join(unique_tools[:5])}",
            "instructions": "\n".join(step_summaries[:10]),
            "proposed_by_agent_id": agent_id,
            "metadata": {
                "tool_sequence": tool_sequence,
                "unique_tools": unique_tools,
                "step_count": len(steps),
                "source_task_id": task_id,
                "discovery_type": "tool_usage_pattern",
            },
        }
        return proposal

    async def submit_proposal(self, proposal: dict) -> str | None:
        """Submit a skill proposal to the SkillGovernor for review.

        Returns the skill ID if proposal is accepted for review, else None.
        """
        try:
            from app.services.skill_governor import SkillGovernor
            governor = SkillGovernor.get_instance()
            return await governor.submit_proposal(proposal)
        except Exception as e:
            logger.error("Failed to submit skill proposal: %s", e)
            return None
