"""Add error_message to Task

Revision ID: 2442c38136ed
Revises: fc305b3c7c1b
Create Date: 2026-03-12 11:12:18.762481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2442c38136ed'
down_revision: Union[str, None] = 'fc305b3c7c1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'error_message')
    # ### end Alembic commands ###
