"""add_conv_id_to_documents

Revision ID: b8fe4fd34b5f
Revises: ddd83123fdea
Create Date: 2026-03-13 00:48:13.192352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
"""add_conv_id_to_documents

Revision ID: b8fe4fd34b5f
Revises: ddd83123fdea
Create Date: 2026-03-13 00:48:13.192352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8fe4fd34b5f'
down_revision: Union[str, None] = 'ddd83123fdea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conversation_id', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_documents_conversation_id'), ['conversation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_conversation_id'))
        batch_op.drop_column('conversation_id')
    # ### end Alembic commands ###
