"""make_model_capabilities_nullable

Revision ID: ddd83123fdea
Revises: b4c9e2a7f1d3
Create Date: 2026-03-13 00:34:28.124083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddd83123fdea'
down_revision: Union[str, None] = 'b4c9e2a7f1d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_registry', schema=None) as batch_op:
        batch_op.alter_column('rpm',
                   existing_type=sa.INTEGER(),
                   nullable=True)
        batch_op.alter_column('tpm',
                   existing_type=sa.INTEGER(),
                   nullable=True)
        batch_op.alter_column('rpd',
                   existing_type=sa.INTEGER(),
                   nullable=True)
        batch_op.alter_column('context_window',
                   existing_type=sa.INTEGER(),
                   nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_registry', schema=None) as batch_op:
        batch_op.alter_column('context_window',
                   existing_type=sa.INTEGER(),
                   nullable=False)
        batch_op.alter_column('rpd',
                   existing_type=sa.INTEGER(),
                   nullable=False)
        batch_op.alter_column('tpm',
                   existing_type=sa.INTEGER(),
                   nullable=False)
        batch_op.alter_column('rpm',
                   existing_type=sa.INTEGER(),
                   nullable=False)
    # ### end Alembic commands ###
